"""Load the masked L2 state for the live assistant in the cloud demo.

The web runtime never sees the raw datasets: ``run_l2`` serializes the
processed (masked) state into ``outputs/l2_web_state.json`` and this module
rebuilds the exact ``L2Context`` objects the assistant needs. Identical
code paths as the local pipeline, plus a re-built sparse index over the
masked documents, so /api/l2/ask answers are generated by the real
deterministic engine on the server.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from kastack.l2_core import ItemRecord, ItemRegistry
from kastack.l2_index import SparseIndex


def load_l2_web_state(out_dir: Path) -> Optional[dict]:
    path = out_dir / "l2_web_state.json"
    if not path.exists():
        return None
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def build_web_context(state: dict):
    """Rebuild a L2Context-like object from the serialized (masked) state."""
    class WebContext:
        pass

    ctx = WebContext()
    registry = ItemRegistry()
    for key, seed in (state.get("seed_keys") or {}).items():
        registry.seed(key, seed["kind"], seed["title"], seed["item_id"])
    for key, d in (state.get("items") or {}).items():
        rec = ItemRecord(d["key"], d["type"], d["title"],
                         d["source_message_id"], d["created_at"])
        for field, value in d.items():
            if field in ("key", "type", "title", "source_message_id",
                         "created_at"):
                continue
            setattr(rec, field, _materialize(value))
        registry.items[key] = rec
        if key not in registry.order:
            registry.order.append(key)
    ctx.registry = registry
    ctx.meta = state.get("meta") or {}
    ctx.message_key = state.get("message_key") or {}
    ctx.decisions = state.get("decisions") or []
    ctx.decision_by_mid = state.get("decision_by_mid") or {}
    ctx.noticeboard = state.get("noticeboard") or []
    ctx.routing = state.get("routing") or []
    ctx.docs = []
    ctx.index = None
    return ctx, set(state.get("demo_ids") or [])


def _materialize(value):
    if isinstance(value, dict):
        return {k: _materialize(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_materialize(v) for v in value]
    return value


def build_web_index(ctx) -> SparseIndex:
    from kastack.l2_pipeline import build_documents
    docs = build_documents(ctx)
    ctx.docs = docs
    index = SparseIndex(docs).build()
    ctx.index = index
    return index